import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

/// Reads the Hardhat artifacts for the user-defined contracts and emits typed
/// ABI exports into web/lib/abis/. Run `pnpm export-abis` after any compile.
const CONTRACTS = ["IdentityRegistry", "SecurityToken", "MockUSDC", "Orderbook"] as const;

const ARTIFACTS_ROOT = join(__dirname, "..", "artifacts", "contracts");
const OUT_DIR = join(__dirname, "..", "..", "web", "lib", "abis");

function camel(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function exportAbi(contractName: string): void {
  const artifactPath = join(ARTIFACTS_ROOT, `${contractName}.sol`, `${contractName}.json`);
  if (!existsSync(artifactPath)) {
    throw new Error(
      `Missing artifact for ${contractName} at ${artifactPath}. Run 'npx hardhat compile' first.`
    );
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const constName = `${camel(contractName)}Abi`;
  const file = `// Auto-generated by contracts/scripts/export-abis.ts — do not edit by hand.\n` +
    `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  const outPath = join(OUT_DIR, `${contractName}.ts`);
  writeFileSync(outPath, file);
  console.log(`  ${contractName} -> ${outPath} (${abi.length} entries)`);
}

function writeIndex(): void {
  const lines = CONTRACTS.map(
    (name) => `export { ${camel(name)}Abi } from "./${name}";`
  ).join("\n");
  writeFileSync(join(OUT_DIR, "index.ts"), lines + "\n");
  console.log(`  index.ts -> ${join(OUT_DIR, "index.ts")}`);
}

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });
  console.log(`Exporting ABIs to ${OUT_DIR}\n`);
  for (const c of CONTRACTS) exportAbi(c);
  writeIndex();
  console.log(`\nDone. ${CONTRACTS.length} ABIs exported.`);
}

main();
